#!/usr/bin/env python3
"""Generate a Locust load-test script from a scenario JSON.

Usage:
    python scripts/gen_locust.py --scenarios scenarios.json --out locustfile.py

Schema (extends qa-perf-design):
  base_url, endpoints{name->{method,path,weight,json,params,headers}},
  scenarios[{name,type,users,spawn_rate,duration,think_time,endpoints:[names]}]
"""
import argparse
import json
import re
import sys


def _cls(name: str) -> str:
    """scenario name -> CamelCase User class name."""
    s = re.sub(r"[^a-zA-Z0-9]+", " ", str(name)).strip()
    return "".join(w.capitalize() for w in s.split()) + "User"


def _py_value(v):
    return json.dumps(v, ensure_ascii=False)


def gen_endpoint_task(ep_name: str, ep: dict) -> str:
    method = (ep.get("method") or "GET").upper()
    path = ep.get("path", "/")
    weight = ep.get("weight", 1)
    body = ep.get("json")
    params = ep.get("params")
    headers = ep.get("headers")
    lines = []
    lines.append(f"    @task({weight})")
    lines.append(f"    def t_{ep_name}(self):")
    kwargs = []
    if body is not None:
        kwargs.append(f"json={_py_value(body)}")
    if params is not None:
        kwargs.append(f"params={_py_value(params)}")
    if headers is not None:
        kwargs.append(f"headers={_py_value(headers)}")
    kw = (", " + ", ".join(kwargs)) if kwargs else ""
    lines.append(f"        self.client.{method.lower()}("
                 f"\"{path}\", name=\"{ep_name}\"{kw})")
    return "\n".join(lines)


def render(data: dict) -> str:
    base_url = data.get("base_url", "https://api.example.com")
    endpoints = data.get("endpoints", {})
    scenarios = data.get("scenarios", [])
    out = []
    out.append("\"\"\"Auto-generated by qa-perf-locust. Edit freely.\"\"\"")
    out.append("from locust import HttpUser, task, between\n")
    out.append(f"BASE_URL = {_py_value(base_url)}\n")

    for s in scenarios:
        cls = _cls(s.get("name", "Scenario"))
        think = float(s.get("think_time", 1.0))
        ep_names = s.get("endpoints", list(endpoints.keys()))
        out.append(f"\nclass {cls}(HttpUser):")
        out.append(f"    host = BASE_URL")
        out.append(f"    wait_time = between({think * 0.5:.2f}, {think * 1.5:.2f})")
        # ramp-up hint as comment + constant
        out.append(f"    # ramp-up: users={s.get('users')} spawn_rate={s.get('spawn_rate')} "
                   f"duration={s.get('duration')}s type={s.get('type')}")
        for epn in ep_names:
            ep = endpoints.get(epn)
            if not ep:
                out.append(f"\n    # WARNING: endpoint '{epn}' not defined")
                continue
            out.append("")
            out.append(gen_endpoint_task(epn, ep))
        out.append("")

    out.append("# Run: locust -f locustfile.py --headless "
               "-u <users> -r <spawn_rate> -t <duration>s --csv=results --html=report.html")
    return "\n".join(out)


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--scenarios", required=True)
    ap.add_argument("--out", required=True)
    args = ap.parse_args()

    try:
        with open(args.scenarios, "r", encoding="utf-8") as f:
            data = json.load(f)
    except Exception as e:
        print(f"[ERROR] 读取场景失败: {e}", file=sys.stderr)
        return 2

    code = render(data)
    with open(args.out, "w", encoding="utf-8") as f:
        f.write(code)
    n = len(data.get("scenarios", []))
    print(f"[OK] 已生成 Locust 脚本: {args.out}（{n} 个 User 类）")
    return 0


if __name__ == "__main__":
    sys.exit(main())
